### ISSUE TITLE
Repository layout: adopt a standard main branch with all the supported versions

### ISSUE THREAD

**Issue by jouvin** [quattor/template-library-os#109]
For reasons I forgot, when we created this repo at SVN -> Git migration time, we opted for a branch per OpenStack version and no master branch. It turned out not to be a great idea: it makes everything more complicated, including:

- A release must tag several branches
- Fixing a problem affecting several middleware versions requires several PRs
- get-template-library must do complicated things to select all the branches to checkout
- Obsoleting a branch requires renaming it with a `.obsolete` suffix rather than removing the corresponding set of templates in the `master` branch

My proposal is to move to a standard structure with a `master` branch and have a first level directory representing the OS version the templates must be used for, e.g. `el7x-x86_64`, `el8x-x86_64`, `el8x-aarch64`... 

Addressing this issue requires:
- [x] Renaming the most recent branch to `main`
- [x] Import the other active branches, preserving their history. https://github.com/hraban/tomono may be a useful tool for achieving this.
- [x] Adapt release tools to the new (simpler) layout
- [x] Update the repository structure description in `get-library-template`

**Comment by jrha** [comment]
I haven't done any work on the release tools yet, but will open a new issue for that.
